version: "3.9"

services:
  
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/localhost.crt:/etc/nginx/ssl/localhost.crt:ro
      - ./nginx/localhost.key:/etc/nginx/ssl/localhost.key:ro
    depends_on:
      - web
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    command:
      - '-nginx.scrape-uri=http://nginx:80/nginx_status'
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - web
      - nginx
      - nginx-exporter
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always

volumes:
  grafana_data:
